name: Guardianbeam
version: '1.2.7-Snapshot'
main: me.guid118.guardianbeam.Guardianbeam
api-version: 1.17
authors: [ guid118, SkytAsul ]
description: can summon guardianbeams in your world!
commands:
  guardianLaserset:
   description: set a guardian laser!
   permission: Guardianbeam.guardianset
   permission-message: You do not have permission!
   usage: /guardianlaserset [x1] [y1] [z1] [x2] [y2] [z2] Duration(Ticks(20/sec)) View-Distance world
  crystalLaserset:
    description: set an end crystal laser!
    permission: Guardianbeam.crystalset
    permission-message: You do not have permission!
    usage: /crystallaserset [x1] [y1] [z1] [x2] [y2] [z2] Duration(Ticks(20/sec)) View-Distance world
  Laserstop:
   description: Stop the laser before its duration has ended
   permission: Guardianbeam.stop
  Fireworks:
   description: Summon fireworks
   permission: Guardianbeam.fireworks.wall
   usage: /fireworks <type>
  Laserpreset:
    description: Summon lasers with a selected preset
    permission: Guardianbeam.preset
    usage: /laserpreset <preset>
  Circle:
    description: makes a circle of particles
    permission: Guardianbeam.circle
  Test:
    description: test commands used to test new things
  Moveend:
    description: moves the end to location provided within provided amount of ticks